### ISSUE TITLE
Crashes with vb.vinylcontrol~

### ISSUE THREAD

**Issue by rconstanzo** [v7b1/vb-objects#1]
Hi,

I'm testing out the `vb.vinylcontrol~` objects and am getting insta crashes (crash reports below). I have some timecode vinyl on the way, but in the meantime I was trying to feed it the Serao Control CD audio (https://serato.com/controlcd/downloads) and was getting loads of crashes.

I was mainly getting crashes when renaming the object from the Max to MSP versions, or while opening the help file with DSP on (but nothing playing back).

I did manage to get it working (I think), where I get valid `pitch` information, as well as some jittery `position` and `timecode`, but if I mess with the playback speed at all, the `position` and `timecode` seem to get lost and stuck. That could be on me though, as I have no idea the expected behavior of those outlets.

This is the code I was using when I got a bunch of crashes:
----------begin_max5_patcher----------
1360.3oc0XssaabCD8YouhE6iEpVjbum2Rc.ReI.EHonnnHvfZEsLioVpxkq
sUBh+1K4vkRT1J5hsLha.xlUyRxYNmY3YHy2FNHdh7NVabzah9mnAC91vAC.
SVCC5+8f34z6pEzVXXwruNkVee7H2mVP00WwalcghUqcKSRZ0YnQQjD3eRy7
Oi9b+b3SgERN4K+ZkecZ5lyaDLM3CxZixNs2JxZ76CGZeL5.C1F1sF23chlc
GDiw+x8QnyvdyNenWtf4.PbKeVCUDuJf2BHSQkVbgKcfDAHlrcPhQGAJwulP
Yep7fPI4kFjcymvTqJ7tT1nanyAvD+VE2fj8.zQQwWJjT8ZDOWNkEFjagAv4
UmkspXN2w.3.FvFGWRqg0A8XVIcmrhcxs7uBSFaV0dyl.FVtUF1j8H++g8Pj
.ofim8xdkvd0x4yYM5GsCSymypszvdo0sPNjzBfOxAxICzIwUaeyUwVIB7tI
hmu74OB2KjsbMW17jvMtfDf6zxcg67WY3laPySCz3DPGwA5jzcA5xeNf1IQ7
DTHrZCSnMy1YqDRRQfTPQ9ijBBakP1ICrfpLAllotf0PmH1P73fXmmhDvBAc
of2pWIgJU7YbixnlMegDbGYsjyDZKuV20va.snzTz9kW21a1+N0rRl8ZT0xG
q85bT7dUfySb60f5trvN3PIcsTYmhcGc.W9ucTAWu7w94RoPHuclPNI.99YY
0Da0JlcmBDBq8Usfu3JFe1UPvksN8boTMm1n2dXDTXj7jqK7YKAqYl1GXVxv
Du0W2tlY2rRIq25Tpl1WbzWc3PypSNG7AymnSZkhNMyjP.eE+AZMuQKauJ52
e2aF+msLU6XkbpInji+3xl5w+gM0wZG+IC2Yxfi+TmpQaAQ63OxTTsL5bSks
RJhda2Tt7gFO+cmcK8ld1AXTtAo9suGxful233Ypc8sVBFPeJnKKuBgHjRbv
2ZYh04LKolPv4Ek9mjQVSEjpbj+YhmrsSWHkKBRh.wZhSi56EsZpl4Y8P9MX
VdSvtY2KQed3ZKmlSReyjytg2rTT6XPx8Qs.kdQ8z3iYisoFXmhj86V6OuMN
KcmWq3HNvcR.W.qUrf27v68AAj09lDTqrSU6Qk+9LA6pmBkrz0k.9a1Egcoh
GkCNTGQNP+fdl9wvjQj83GB4D4H7dbT5IxO6i3xNA9I4.vylXVplZNiwO7Jf
GiiQGfiQ+LbLY6NF8xS0n86Y2te5hE2X5A0OcvoFgvuHggWNB9Iuw8SPYNVw
tg6GOzULlpLxWZi1Umx0l4tb2scgSmnZ538zsAtFW1pWJdnhy5CXZa57Qide
W6Eef0z4j1Lv7RZmPuI0LYlo6jQJV3BuvVxd42X2WG46T6Gqs8DoJEiKgtRX
SGob3MyKYYADb+bv9IklkVgfVYo4jhzL3sRRRVh8MzClFYsuP3JmGPUknT2a
FSXiuBml4zytyqPJVcHRSsgRtPpVcdnyRpVM9NsblhNkaukhOCupk2n9JKk4
q.sCbROmN2Pnb+bBqDWkLttUvMIv+xlc2UhHfVwP+pvGdkkmYr3ZH+ahNlue
21iEZcMyd.xfDcBtHOsvR44qxdUVS3Wf.TIus4niv0wUlo9KsxcToWlH77kz
iO.QjprTn9snHIg.jYIAatL6oO.euhwdBQHvdI1+XeCmWlaCyScv82L6MdN5
nqjjgARqnDWhAohLCilswt+MtypYqDwNHDp7TA.3Z8uWJldzgusTDAo+rJBN
CPBNT95jDfJmbiMBOP0FyNmz77jp9xwhBWgogXqR1jZmL6kFPt9ovMHrHpcQ
++alvEMF98g+GYS01jC
-----------end_max5_patcher-----------

And here are two crash reports that I saved from crashes when renaming the object and/or playing audio through `vb.vinylcontrol2~`.

[crashes.zip](https://github.com/v7b1/vb-objects/files/5182837/crashes.zip)

I'm on MacOS 10.14.6 on Max 8.1.5 and if it's of use, here is my Max "support" copy/paste:

```{
	"version" : "Version 8.1.5 (9359645) (64-bit mac)",
	"platform" : "mac",
	"arch" : "x64",
	"osversion" : "Mac OS X Version 10.14.6 (Build 18G103) x86_64",
	"samplerate" : 44100,
	"iovs" : 64,
	"sigvs" : 64,
	"scheduler_in_audio_interrupt" : "off",
	"audio_drivername" : "Core Audio",
	"audio_driver_subname" : "",
	"license" : "permanent full",
	"machine_id" : "xxx",
	"eventinterval" : 2,
	"schedinterval" : 1.0,
	"overdrive" : "off",
	"pollthrottle" : 40,
	"queuethrottle" : 100,
	"sysqelemthrottle" : 1000,
	"refreshrate" : 33.333332061767578,
	"schedslop" : 25.0,
	"eventprobing" : 1,
	"mixerparallel" : "off",
	"mixercrossfade" : 0,
	"mixerlatency" : 30.0,
	"mixerramptime" : 10.0,
	"videoengine" : "avf",
	"glengine" : "gl2",
	"packages" : 	{
		"AudioMix" : "1.0.2",
		"BEAP" : "1.0.3",
		"BLOCKS" : "1.2.7",
		"cage" : "0.6.0",
		"CNMAT Externals" : "1.0.4",
		"dada" : "0.2.1",
		"Digital Orchestra Toolbox" : "1.1.1",
		"ease" : "1.1.1",
		"Fluid_Decomposition" : "TB2-Alpha05",
		"FrameLib" : "2.1",
		"hap" : "1.0.6",
		"HISSTools Impulse Response Toolbox (HIRT)" : "2.0.1",
		"imp.dmx" : "0.5",
		"jit.mo" : "1.1.2",
		"karma" : "1.0.0",
		"max-mxj" : "7.2.5",
		"MC Movement Studies" : "1.0.0",
		"Mira" : "1.2.1",
		"Miraweb" : "1.2.5",
		"ml.star" : "1.2.1",
		"monome" : "0.0.2",
		"MuBu For Max" : "1.9.12",
		"Node For Max" : "1.3.2",
		"orchidea" : "0.6",
		"PowerMax" : "",
		"smFilterPack" : "0.0.3",
		"vb.mi-objects" : "0.0.1",
		"VIDDLL" : "1.2.3",
		"Video & Graphics" : "7.2.0",
		"Vizzie" : "2.1.0"
	}

}
```

**Comment by v7b1** [comment]
Hi, and thanks for the report, which I can (partly) reproduce here. I have an idea where the crashes are coming from, but need some more time to investigate further.

**Comment by v7b1** [comment]
ok, crashes should be fixed. please re-dwnl and report back.
[vb.vinylcontrol~.zip](https://vboehm.net/maxobjects/vb.vinylcontrol~.zip)

**Comment by rconstanzo** [comment]
Awesome, no crashes or anything.

Great timing too, as I think my timecode vinyl arrives tomorrow, so I'll report back if there's any crashing with that, but it seems unlikely as this appears to be stable.

**Comment by rconstanzo** [comment]
All good with timecode vinyl. I still need to get my head around the signals and how to best use them, but no crashes!
