### ISSUE TITLE
vb.stretch not included?

### ISSUE THREAD

**Issue by J-Fo-S** [v7b1/vb-objects#3]
Hello, 
Big admirer of your vb.stretch object, and now that my mac died I was planning on compiling it for windows. However, if I'm not missing something it seems to not be included in the repo here. How may I get a hold of the source to comp it for windows? Many thanks!

**Comment by v7b1** [comment]
Hi - yes, not all of my creations are open source (yet). On top of that, vb.stretch for windows would need a major re-write, as it makes heavy use of Apple's vdsp lib. I'm working on it, from time to time, but can't make any promises.
